# Site Settings
baseurl: ""
url : "https://mcubescloud.tk"
date_format: "%Y-%m-%d"
read_time: true
words_per_minute: 200
mathjax: true

# Blog Settings
theme_settings :
  title : MCUBES-Cloud
  favicon : assets/Logo.ico

  # Profile Settings
  profile :
    image : assets/img/getProfileImage.png
    username : Mohamed.S
    description : Blogger, Freelauncher, Cloud, Scripting, Operations and Python-Julia Learner.
    experience :
      - start : 2016-12-01
        end : 2017-04-01
        experience : KGISL, RIMS
      - start : 2017-05-01
        end : Till date
        experience : PUC, L&T. Cloud Engineer
    skills : 
      - skill : AWS, GCP and AZURE
        value : 90  # Percent value
      - skill : Docker, kubernetes
        value : 90  # Percent value
      - skill : Windows, Linux
        value : 90  # Percent value
      - skill : Bash Script and Powershell
        value : 95  # Percent value
      - skill : Python and Julia
        value : 70  # Percent value
      - skill : CI-CD Tools
        value : 80  # Percent value
  # Icons
  icons :
    email: mcubesmdy@gmail.com  # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: mdy007
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:
  
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

  # Disqus
  disqus_shortname : Mcubes
  
  #google_analytics
  google_analytics: "UA-154897508-1"
  
  # Search
  search_full_content: true

# Pagination
paginate: 5
paginate_path: "blog/page:num"


# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
footer_links:
  - title: Linkedin
    url: https://www.linkedin.com/in/mohamed-s-98669774/
    icon: linkedin
copyright: "©2019 Mcubes All Right Reserved. "
