# Site Settings
baseurl: ""
url : "https://mcubescloud.tk"

# Blog Settings
theme_settings :
  title : MCUBES-Cloud
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/getProfileImage.png
    username : Mcubes Mdy
    description : Blogger, Freelauncher, Cloud, Scripting and Developer
    experience :
      - start : 2017-12-01
        end : Till date
        experience : Puc, L&T. Cloud Engineer
    skills : 
      - skill : AWS, GCP and AZURE
        value : 90  # Percent value
      - skill : Docker, kubernetes
        value : 90  # Percent value
      - skill : Windows, Linux
        value : 90  # Percent value
      - skill : Bash Script and Powershell
        value : 95  # Percent value
      - skill : Python and Julia
        value : 70  # Percent value
      - skill : CI-CD Tools
        value : 80  # Percent value
  # Icons
  icons :
    email: mcubesmdy@gmail.com  # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: mdy007
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname : Mcubes
  
  # Search
  search_full_content: true

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
